### ISSUE TITLE
Improve error handling in calldata decoder

### ISSUE THREAD

**Issue by krzkaczor** [dethcrypto/dethtools#62]
1. Why is huge rectangle visible when there are no matches? 
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/1814312/177554358-9c30b559-6a13-4152-a511-683959130f70.png">
2. No error handling when providing ABi by hand:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/1814312/177554510-fc57ef0d-04d6-40c4-91ee-fd89a6aa4742.png">

**Comment by 7sne** [comment]
Resolved in #64, #66, #67.
